sources:
    HongkongLand: https://deliver.kenticocloud.com/a17cc544-9497-008c-8c42-28f962783f7a/items?system.type=property_details_page_v2&language=en
    AXAIM: https://graphql.umbraco.io
    AryadutaHotelGroup: https://www.aryaduta.com/xax/property/group/city?_=1710169411850&status=active
